---

# - name: install python
#   ansible.builtin.package:
#     name: "{{ common_packages_to_install }}"
#     state: present

- name: install python3
  ansible.builtin.package:
    name: python3
    state: present

- name: install python3-apt
  ansible.builtin.package:
    name: python3-apt
    state: present

- name: install python3-pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: install general python packages
  pip:
    name: "{{ python_generic_packages }}"
# - name: install ufw on basebox
#   apt:
#     name: ufw
#     state: present

#- name: install mysql
#  apt:
#    name: mysql-server
#    state: present
