---
- hosts: all
  become: yes
  tasks:
    - name: clone shell
      git:
        repo: "https://github.com/victorarjona2/shell"
        dest: /home/sysadmin/code/shell
        update: yes

    - name: clone python_scripts
      git:
        repo: "https://github.com/victorarjona2/python_scripts"
        dest: /home/sysadmin/code/python_scripts
        update: yes

    - name: clone scilab
      git:
        repo: "https://github.com/victorarjona2/scilab"
        dest: /home/sysadmin/code/scilab
        update: yes

- hosts: master-node
  become: yes
  tasks:
     - name: clone ansible
       git:
        repo: "https://github.com/victorarjona2/ansible"
        dest: /home/sysadmin/code/ansible
        update: yes

     - name: clone robot_framework
       git:
        repo: "https://github.com/victorarjona2/robot_framework"
        dest: /home/sysadmin/code/robot_framework
        update: yes
