---
- hosts: fs-nodes
  become: yes
  tasks:
    - name: install nfs-kernel-server
      apt:
        name: nfs-kernel-server
        state: latest
# TODO: ADD NFS EXPORTATION!
#    - name: export nfs share
- hosts: fs-client-nodes
  become: yes
  tasks:
    - name: install nfs-common
      apt:
        name: nfs-common
        state: latest
    - name: mkdir /clusterfs
      file:
        path: /clusterfs/
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777
        recurse: yes
    - name: add nfs element in to /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: "192"
        line: 192.168.0.102:/clusterfs	/clusterfs	nfs	defaults	0	0
    - name: mount all
      shell:
        cmd: mount -a
