---
- hosts: rpi-nodes
  become: yes
  tasks:
    - name: rpi-nodes | create cluster-python-env and install packages
      pip:
        name:
          - setuptools
          - numpy
          - pandas
          - matplotlib
          - bs4
          - tensorflow
          - mpi4py
        virtualenv_python: python3
        virtualenv: /home/sysadmin/cluster-python-env
