---
- name: setup cockpit nodes
  block:
    # Install cockpit + other cockpit services.
    - name: install cockpit
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items: "{{ cockpit_extras }}"
        
    - name: setup cockpit node ports
      block:
        - name: close ports with firewalld
          firewalld:
            port: "{{ item }}"
            state: disabled
            immediate: True
            permanent: True
          with_items: "{{ cockpit_webserver_ports }}"

    # Disable Cockpit Services
    - name: disable cockpit services
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - cockpit.socket
        - cockpit.service
      when:
        - "'master_nodes' not in group_names"

#    - name: confirm only selected hosts are webservers