---
- name: install and setup cockpit
  block:
    # Install cockpit + other cockpit services.
    - name: install cockpit
      ansible.builtin.package:
        name: 
          - cockpit
        state: present

    # Ensure necessary ports are open.
      # Cockpit Webservers (personal computer + one extra computer) should have all necessary ports.
      # Cockpit Machines should NOT have Cockpit Webservers enabled.

    # Restart Cockpit Services

    # Ensure only master machines host Cockpit Webservers