---
- hosts: all
  become: yes
  tasks:
    - name: install git
      apt:
        name: ["git"]
        state: latest
    - name: install htop | vim | nmap | cowsay | nfs-common
      apt: 
        name: ["htop", "vim", "nmap", "cowsay", "nfs-common"]
        state: latest
- hosts: rpi-nodes
  become: yes
  tasks:
    - name: install wiringpi
      apt:
        name: ["wiringpi"]
        state: latest
- hosts: master-node
  become: yes
  tasks:
    - name: install robot framework
      pip:
        name:
          - robotframework
        executable: pip3
