---
- hosts: all
  become: yes
  tasks:
    - name: install gcc | gfortran | python | python3
      apt:
        name: ["gcc", "gfortran", "python2", "python3"]
        state: latest
    - name: install python stuff
      apt:
        name: ["python-setuptools", "python3-pip", "ipython3", "python3-setuptools", "python3-dev", "libopenmpi-dev"]
        state: latest
#    - name: upgrade pip to latest
#      shell:
#        cmd: pip install -U pip
#    - name: upgrade pip3 to latest
#      shell:
#        cmd: pip3 install -U pip
    - name: install python packages
      pip:
        name:
          - pandas
          - numpy
          - matplotlib
          - jupyter
        executable: pip3
#    - name: install mpich
#      apt:
#        name: ["mpich"]
#        state: latest
#    - name: install python3-mpi4py
#      apt:
#        name: ["python3-mpi4py"]
#        state: latest
