---
- hosts: truly-all-non-rpi-nodes
  become: yes
  tasks:
    - name: truly-all-non-rpi-nodes | create cluster-python-env and install packages
      pip:
        name:
          - setuptools
          - numpy
          - pandas
          - matplotlib
          - bs4
          - tensorflow
          - mpi4py
        virtualenv_python: python3
        virtualenv: /home/sysadmin/cluster-python-env
