---
# FirewallD was selected as the de-facto firewall service because it works with
#   Cockpit service, it is Open Source, and there is an Ansible module to
#   manage it. On the other hand, RPi 3B+ doesn't work very well with FirewallD.
#   So might as well have both readily available and test
- name: ensure ufw is installed
  ansible.builtin.package:
    name: "ufw"
    state: latest

# In the defaults
- name: setup ports
  block:
    - name: enable port for "{{ item['label'] }}"
      community.general.ufw:
        rule: allow
        port: "{{ item['port'] }}"
        state: enabled
        proto: "{{ item['protocol'] }}"
        comment: "{{ item['label'] }}"
      with_items:
        - "{{ firewall_default_allowed_ports }}"


# Enable FirewallD
# - name: enable firewalld
#   ansible.builtin.service:
#     name: "firewalld"
#     state: enabled
