---

ufw_files_needed:
  - "/etc/ufw/before.rules"
  - "/etc/ufw/before6.rules"
  - "/etc/ufw/after.rules"
  - "/etc/ufw/after6.rules"

firewall_default_allowed_ports:
  - "port": ""
    "protocol": ""
    "comment": ""
    "rule": ""

# From https://docs.pi-hole.net/main/prerequisites/
pihole_default_allowed_ports:
  - "port": "53"
    "protocol": "tcp"
    "comment": "DNS"
    "rule": "allow"

  - "port": "67"
    "protocol": "tcp"
    "comment": "DHCP"
    "rule": "allow"

  - "port": "547"
    "protocol": "tcp"
    "comment": "DHCPv6"
    "rule": "allow"

  - "port": "80"
    "protocol": "tcp"
    "comment": "HTTP"
    "rule": "allow"

  - "port": "4711"
    "protocol": "tcp"
    "comment": "FTL"
    "rule": "deny"
