---

- name: install ufw and set files in place
  block:
    - name: ensure ufw is installed
      ansible.builtin.package:
        name: "ufw"
        state: latest

    - name: list all files in /etc/ufw/
      ansible.builtin.find:
        paths: /etc/ufw/
        recurse: no
        file_type: file
      register: list_ufw_files_return

    - name: ensure default needed files exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: touch
        mode: "0640"
      loop: "{{ ufw_files_needed }}"
      when: "item not in {{ list_ufw_files_return['files'] | map(attribute='path') | list }}"
