---
cockpit_webserver_pkgs:
  - cockpit
  - cockpit-podman

rpi_cockpit_webservers_pkgs:
  - cockpit

cockpit_webserver_ports:
  - "port": "9090"
    "protocol": "tcp"

cockpit_socket_override_conf_dir: "/etc/systemd/system/cockpit.socket.d/"